name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - Hexo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.HEXO_GITHUB_TOKEN }} # secret 名
          PUBLISH_REPOSITORY: zhang-wen-tao/zhang-wen-tao.com
          BRANCH: Hexo_Github_Pages
          PUBLISH_DIR: ./public
